config/routes.rb
Rails.application.routes.draw do
  resources :polls do
    member do
    put "like", to: "polls#upvote"
    #put "dislike", to: "links#downvote"
  end
  end
  resources :reports
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :locations
  resources :problematics do
    resources :solutions
  end




  # resources :articles , except: [:delete] o , only: [:create] // en este cas este comando genera todas las rutas para CRUD del modelo Articles
  #Y es este caso se epecifica que se crearan todas las rutas excepto la de borrar

  get 'welcome/index'
  #get "especial", to: "welcome#index"// este comando genera que la ruta /especial sea igual que
  # escribir welcome#index

  root 'welcome#index'
  # direcciona a esta ruta la raiz de la url
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :location
  acts_as_votable
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]


  # GET /polls
  # GET /polls.json
  def upvote
    @poll = Poll.find(params[:id])
    current_user.likes @poll

    if params[:opcion]=='opcion1'
      current_user.likes @poll , :vote_scope => 'opcion1'
      #@poll.liked_by current_user, :vote_scope => 'opcion1'

    elsif params[:opcion]=='opcion2'
      current_user.likes @poll , :vote_scope => 'opcion2'
      #@poll.liked_by current_user, :vote_scope => 'opcion2'

    elsif params[:opcion]=='opcion3'
      current_user.likes @poll , :vote_scope => 'opcion3'
      #@poll.liked_by current_user, :vote_scope => 'opcion3'

    elsif params[:opcion]=='opcion4'
      current_user.likes @poll , :vote_scope => 'opcion4'
      #@poll.liked_by current_user, :vote_scope => 'opcion4'

    end
    redirect_to poll_path(params[:id])

  end

  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @location = Location.find(current_user.location_id)
    @poll = @location.poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:location_id, :nombre_po, :pregunta, :opcion1, :opcion2, :opcion3, :opcion4, :categoria_po, :usuario)
    end
    def vote_params
      params.require(:poll).permit( :opcion,:id)
    end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<div class="form-group mx-auto" >
  <%= form_with(model: poll, local: true) do |form| %>
    <% if poll.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

        <ul>
        <% poll.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field align-baseline">
      <%= form.label :nombre_de_La_Consulta , class:"font-weight-bold border rounded p-1 border-dark m-2"%>
      <p class="">Asigna un nombre que identifique la nueva encuesta</p>
      <%= form.text_field :nombre_po ,autofocus: true, class:"form-control w-50"%>
    </div>

    <div class="field">
      <%= form.label :pregunta, class:"font-weight-bold border rounded p-1 border-dark mb-2 mt-4" %>
      <p> </p>
      <%= form.text_area :pregunta,autofocus: true, class:"form-control",rows:"5" %>
    </div>

    <div class="field">
      <%= form.label :Primera_opcion, class:"font-weight-bold border rounded p-1 border-dark mb-2 mt-4" %>

      <%= form.text_area :opcion1,autofocus: true, class:"form-control",rows:"2" %>
    </div>
    <div class="field">
      <%= form.label :Segunda_opcion, class:"font-weight-bold border rounded p-1 border-dark mb-2 mt-4" %>

      <%= form.text_area :opcion2,autofocus: true, class:"form-control",rows:"2" %>
    </div>
    <div class="field">
      <%= form.label :Tercera_opcion, class:"font-weight-bold border rounded p-1 border-dark mb-2 mt-4" %>

      <%= form.text_area :opcion3,autofocus: true, class:"form-control",rows:"2" %>
    </div>
    <div class="field">
      <%= form.label :Cuarta_opcion, class:"font-weight-bold border rounded p-1 border-dark mb-2 mt-4" %>

      <%= form.text_area :opcion4,autofocus: true, class:"form-control",rows:"2" %>
    </div>


    <div class="field ">
      <%= form.label :categoria,class:"font-weight-bold text-light border rounded p-1 border-light mb-2 mt-4" %><br />
      <p>Seleccion la categoria a la cual pertenece tu encuesta</p>
      <%= form.select(:categoria_po, options_for_select([['Movilidad','Movilidad'], ['Contaminacion', 'Contaminacion'], ['Seguridad', 'Seguridad'],['Cultura y Recreacion', 'Cultura y Recreacion'],], 1), class:"form-control ") %>

    </div>

      <%= form.hidden_field :usuario, :value => current_user.nombre_us %>

    <div class="actions my-3 text-center">
      <%= form.submit "Crea la nueva Consulta", class:"btn btn-warning " %>
    </div>
  <% end %>

</div>

app/views/polls/edit.html.erb
<div class=" jumbotron  form-problematic  mx-5 " >
  <h2 class=" display-4 font-italic font-weight-bold text-center mb-3">Edita la  Consulta</h2>


<%= render 'form', poll: @poll%>
</div>
<%= link_to 'Back', {:controller => "polls", :action => "index", :categoria_po => "all"}, class:"btn btn-outline-dark m-5" %> |

app/views/polls/index.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded mx-5 d-flex flex-row " style="background:#1d1e22;">
      <div class="col-md-6 px-0 mr-5 ">
        <div class="display-4 font-italic d-flex " style="">
          <i class="fa fa-clipboard"></i> <h1 class="mx-3 mt-2">Encuestas&nbsp;</h1>
        </div>
        <p class="lead my-3">Por medio de las encuestas cada represéntate pondrá a	 consulta los asuntos  de mayor interés.
      De esta forma cada representante lograra medir el sentimiento de la comunidad frente a temas concernientes a la movilidad,
      seguridad contaminación y recreación.
      .</p>
      </div>
      <div class="input-group my-auto ml-5 d-flex flex-row">

        <div class="">
          <%= form_tag({:controller => "problematics", :action => "index"}, :method => "get") %>


          <%= select_tag(:categoria_pr, options_for_select([['Todas', 'all'],['Movilidad','Movilidad'], ['Contaminacion', 'Contaminacion'], ['Seguridad', 'Seguridad'],['Cultura y Recreacion', 'Cultura y Recreacion'],], 5), class:" custom-select" )%>
        </div>
        <div class="">
        <%= submit_tag "Filtrar" , class:"btn btn-warning mx-2" %>
        </div>

     </div>
</div>


<div class="w-75 mx-auto ">
  <% @polls.each do |poll| %>
  <div class="d-flex  text-light mb-3 rounded" style="background:#1d1e22; ">
    <div class="flex-grow-1 p-2 d-flex">
      <h3 class=""> <%= poll.nombre_po %></h3> <p class="ml-3 text-muted">Consulta #<%= poll.id %></p>
    </div>
    <div class="p-2 ">
      <p class="my-auto  " style="color:#FF5A09; "><%= poll.categoria_po %></p>
    </div>
    <div class="p-2 my-auto">
      <button type="button" class="btn btn-outline-light">
        <%= link_to 'Participar', poll %>
        <span class="badge badge-info"><%=poll.votes_for.size%> votos</span>
      </button>

    </div>
  </div>
  <% end %>
</div>

<div class="mx-auto " style="width:300px;">
  <% if current_user.roll == 'Representante'%>
  <%= link_to 'Crea un nueva consulta', new_poll_path, class:"btn btn-warning my-5" %>
  <%end%>
</div>

app/views/polls/new.html.erb
<div class=" jumbotron  form-problematic  mx-5 " >
  <h2 class=" display-4 font-italic font-weight-bold text-center mb-3">Nueva Consulta</h2>


<%= render 'form', poll: @poll%>
</div>
<%= link_to 'Back', {:controller => "polls", :action => "index", :categoria_po => "all"}, class:"btn btn-outline-dark m-5" %> |

app/views/polls/show.html.erb
<div class=" mx-5 mb-5">
  <div class="display-2">
    <i class="fa fa-clipboard"></i>

  </div>
  <p>Creada:<%= @poll.created_at %></p>
  <div class="row ">
    <strong class="display-4 d-flex-inline"><%= @poll.nombre_po %></strong> <p class="d-flex-inline mt-4 ml-3 mr-1">por </p> <p class="text-info  mt-4 "> <%= @poll.usuario %> </p>

  </div>



  <p class="lead"> <%= @poll.pregunta %></p>


  <%= form_tag(like_poll_path(@poll.id), :method => "put") %>
  <div class="row">
    <div class="col">
      <div class="input-group my-2">
        <div class="input-group-prepend">
          <div class="input-group-text">
            <%= radio_button_tag(:opcion, "opcion1", class:"") %>
          </div>
        </div>
        <%= label_tag(@poll.opcion1, @poll.opcion1, class:"form-control")  %>
      </div>
    </div>

    <div class="col ">

      <% if current_user.voted_for? @poll%>
      <div class=" mt-2  d-flex-inline  rounded  w-25 text-center" style="border-color:#FF5A09; border-style: outset;">
        <strong>Votos:</strong>
        <strong class="text-success">  <%= @poll.get_likes(:vote_scope=>'opcion1').size%></strong>
      </div>
      <% end %>
    </div>

  </div>


  <div class="row">
    <div class="col">
      <div class="input-group my-2">
        <div class="input-group-prepend">
          <div class="input-group-text">
            <%= radio_button_tag(:opcion, "opcion2", class:"") %>
          </div>
        </div>
        <%= label_tag(:opcion2, @poll.opcion2, class:"form-control") %>
      </div>
    </div>
    <div class="col">
      <% if current_user.voted_for? @poll%>
      <div class=" mt-2  d-flex-inline  rounded w-25 text-center" style="border-color:#FF5A09; border-style: outset;">
        <strong>Votos:</strong>
        <strong class="text-success">  <%= @poll.get_likes(:vote_scope=>'opcion2').size%></strong>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="input-group my-2">
        <div class="input-group-prepend">
          <div class="input-group-text">
            <%= radio_button_tag(:opcion, "opcion3", class:"") %>
          </div>
        </div>
        <%= label_tag(:opcion3, @poll.opcion3, class:"form-control") %>
      </div>
    </div>
    <div class="col">
      <% if current_user.voted_for? @poll%>
      <div class=" mt-2  d-flex-inline  rounded  w-25 text-center" style="border-color:#FF5A09; border-style: outset;">
        <strong>Votos:</strong>
        <strong class="text-success">  <%= @poll.get_likes(:vote_scope=>'opcion3').size%></strong>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="input-group my-2">
        <div class="input-group-prepend">
          <div class="input-group-text">
            <%= radio_button_tag(:opcion, "opcion4", class:"") %>
          </div>
        </div>
        <%= label_tag(:opcion4, @poll.opcion4, class:"form-control") %>
      </div>
    </div>
    <div class="col">
      <% if current_user.voted_for? @poll%>
      <div class=" mt-2  d-flex-inline  rounded  w-25 text-center" style="border-color:#FF5A09; border-style: outset;">
        <strong>Votos:</strong>
        <strong class="text-success">  <%= @poll.get_likes(:vote_scope=>'opcion4').size%></strong>
      </div>
      <% end %>
    </div>
  </div>

  <%= hidden_field_tag :id, :value => @poll.id %>

  <div class="input-group-prepend">
      <% if !current_user.voted_for? @poll%>
      <%= submit_tag "Enviar" , class:"btn btn-warning my-2" %>
      <% else %>
      <p class="text-success lead">Gracias por participar!</p>
      <% end %>

  </div>

</div>

<div class="m-5">
  <%= link_to 'Back', polls_path, class:"btn btn-outline-dark" %>
  <% if current_user.roll == 'Representante'%>
    <%= link_to 'Edit', edit_poll_path(@poll),class:"btn btn-outline-info" %> |
    <%= link_to 'Destroy', @poll, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-outline-danger"%>
  <%end%>
</div>