config/routes.rb
Rails.application.routes.draw do
  resources :polls do
    member do
    put "like", to: "polls#upvote"
    #put "dislike", to: "links#downvote"
  end
  end
  resources :reports
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :locations
  resources :problematics do
    resources :solutions
  end




  # resources :articles , except: [:delete] o , only: [:create] // en este cas este comando genera todas las rutas para CRUD del modelo Articles
  #Y es este caso se epecifica que se crearan todas las rutas excepto la de borrar

  get 'welcome/index'
  #get "especial", to: "welcome#index"// este comando genera que la ruta /especial sea igual que
  # escribir welcome#index

  root 'welcome#index'
  # direcciona a esta ruta la raiz de la url
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/problematic.rb
class Problematic < ApplicationRecord
  validates :nombre_pr,  presence: true

  belongs_to :location
  has_many :solution
  has_one_attached :image
  
end

app/controllers/problematics_controller.rb
class ProblematicsController < ApplicationController
  before_action :set_problematic, only: [ :show, :edit, :update, :destroy]


  # GET /problematics
  # GET /problematics.json



  def index

    #@problematics=Problematic.joins(thematic: :location).where("thematic_id = ? AND thematics.location_id = ?" , session[:thematic_id], session[:location_id])

    #session[:location_id]=params[:id]
    #@problematics = Problematic.where(nil)


    if !params[:categoria_pr].present? || params[:categoria_pr] =="all"
      @problematics = Problematic.where("location_id = ?" , current_user.location_id)

    else
      @problematics = Problematic.where("location_id = ? AND categoria_pr = ?" , current_user.location_id, params[:categoria_pr])

    end

  #  @problematics = Problematic.categoria_pr(params[:categoria_pr]) if params[:categoria_pr].present?

    #@locations = Location.find(params[:location_id])
    #@problematics = @thematics.problematic
  end


  # GET /problematics/1
  # GET /problematics/1.json
  def show
  #   render 'show.json.jbuilder'

  end

  # GET /problematics/new
  def new

    @problematic = Problematic.new
  end

  # GET /problematics/1/edit
  def edit
  end

  # POST /problematics
  # POST /problematics.json
  def create

    @location = Location.find(current_user.location_id)
    @problematic = @location.problematic.new(problematic_params)
    @problematic.image.attach(params[:problematic][:image])
    respond_to do |format|
      if @problematic.save
        format.html { redirect_to @problematic, notice: 'Problematic was successfully created.' }
        format.json { render :show, status: :created, location: @problematic }
      else
        format.html { render :new }
        format.json { render json: @problematic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problematics/1
  # PATCH/PUT /problematics/1.json
  def update
    respond_to do |format|
      if @problematic.update(problematic_params)
        format.html { redirect_to @problematic, notice: 'Problematic was successfully updated.' }
        format.json { render :show, status: :ok, location: @problematic }
      else
        format.html { render :edit }
        format.json { render json: @problematic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problematics/1
  # DELETE /problematics/1.json
  def destroy
    @problematic.destroy
    respond_to do |format|
      format.html { redirect_to problematics_url, notice: 'Problematic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    def set_problematic
      @problematic = Problematic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problematic_params

      params.require(:problematic).permit(:nombre_pr, :descripcion_pr, :te_perjudica, :usuario, :categoria_pr)
    end
end

app/helpers/problematics_helper.rb
module ProblematicsHelper
end

app/views/problematics/_form.html.erb
<div class="form-group mx-auto" >
  <%= form_with(model: problematic, local: true) do |form| %>
    <% if problematic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(problematic.errors.count, "error") %> prohibited this problematic from being saved:</h2>

        <ul>
        <% problematic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field align-baseline">
      <%= form.label :nombre_de_problematica %>
      <p class="">Asigna un nombre que identifique la nueva problematica</p>
      <%= form.text_field :nombre_pr ,autofocus: true, class:"form-control"%>
    </div>

    <div class="field">
      <%= form.label :descripcion_de_problematica %>
      <p>Entre mas detalles de la problematica que propones tendra una mejor acogida,
        No escatimes en detalles, especifica ubicacion, a quien afecta y hasta una posible solucion. </p>
      <%= form.text_area :descripcion_pr,autofocus: true, class:"form-control",rows:"10" %>
    </div>

    <div class="field text-center">
      <%= form.label :carga_imagen %>
      <p>Carga una imagen para dar mayor detalle de la problematica propuesta</p>
      <%= form.file_field :image, class:"form-control align-middle" %>

    </div>

      <%= form.hidden_field :usuario, :value => current_user.nombre_us %>

    <div class="actions my-3 ">
      <%= form.submit "Crea la nueva problematica", class:"btn btn-warning " %>
    </div>
  <% end %>

</div>

app/views/problematics/_form_index.html.erb
<% if false%>
  <div class="text-center border-left border-right w-25 mx-auto  titulo-localidad border-dark " >
    <h2 >  <%=Location.find(current_user.location_id).nombre_loc %></h2>
  </div>
  <%end%>

  <div class="jumbotron p-3 p-md-5 text-white rounded mx-5 d-flex flex-row " style="background:#1d1e22;">
        <div class="col-md-8 px-0 mr-5 ">
          <div class="display-4 font-italic d-flex " style="">
            <i class="fa fa-comments "></i> <h1 class="mx-3 mt-2">PROBLEMÁTICAS&nbsp;</h1>
          </div>
          <p class="lead my-3 text-justify">Como ciudadano puedes crear una problemática o iniciativa que afecte a tu localidad.
            En cada problemática tienes la opción para dejar un comentario o posible solución.
            Si te afecta determinada problemática dale al botón ¿me perjudica? para que el representante de tu localidad se entere de las problemáticas mas apremiantes
            </p>
        </div>
        <div class="input-group my-auto ml-5 d-flex flex-row ">

            <div class="">
              <%= form_tag({:controller => "problematics", :action => "index"}, :method => "get") %>

            </div>

            <div class=" ">

              <%= select_tag(:categoria_pr, options_for_select([['Todas', 'all'],['Movilidad','Movilidad'], ['Contaminacion', 'Contaminacion'], ['Seguridad', 'Seguridad'],['Cultura y Recreacion', 'Cultura y Recreacion'],], 5), class:" custom-select" )%>

            </div>
            <div class="mt-3">
              <%= submit_tag "Filtrar" , class:"btn btn-warning mx-2 " %>

            </div>


       </div>
  </div>



<div class="mb-3 mx-5 p-3 bg-white rounded border box-shadow">

        <h6 class="border-bottom border-gray pb-2 mb-0">Recent updates</h6>
        <% @problematics.each do |problematic| %>
        <div class="media text-muted pt-3 border-bottom border-gray">

          <%if problematic.image.attached? %>
            <%= image_tag problematic.image ,class:"mr-2 rounded", alt:"Thumbnail [32x32]" , style:"width: 32px; height: 32px;"%>
          <%else %>
              <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_166acb18bbf%20text%20%7B%20fill%3A%23e83e8c%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_166acb18bbf%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23e83e8c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2211.546875%22%20y%3D%2216.9%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
          <%end %>


          <p class="media-body pb-3 mb-0 small lh-125  border-gray">
            Problematica # <%= problematic.id %>
            <strong class="d-block text-dark"><%= problematic.nombre_pr %></strong>
            <strong class="d-block text-gray-dark">  Categoria: <%= problematic.categoria_pr %></strong>

          </p>
          <div class=" ml-auto "><%= link_to 'Mas detalles', problematic_path(problematic) , class:"btn btn-outline-danger", style:" border: #FF5A09"%></div>

        </div>

        <% end %>
      </div>

      <div class="mx-auto " style="width:300px;">
        <%= link_to 'Crea un nueva problematica', new_problematic_path, class:"btn btn-warning my-5" %>

      </div>

app/views/problematics/edit.html.erb
<h1>Editing Problematic</h1>

<%= render 'form', problematic: @problematic %>

<%= link_to 'Show', @problematic %> |
<%= link_to 'Back', problematics_path %>

app/views/problematics/index.html.erb
<%= render 'form_index' %>

app/views/problematics/new.html.erb
<div class=" jumbotron  form-problematic  mx-5 " >
  <h2 class=" display-4 font-italic font-weight-bold text-center mb-3">Nueva problemática</h2>


<%= render 'form', problematic: @problematic %>
</div>
<%= link_to 'Back', {:controller => "problematics", :action => "index", :categoria_pr => "all"}, class:"btn btn-outline-dark m-5" %> |

app/views/problematics/show.html.erb
<% if false%>
<div class="text-center border-left border-right w-25 mx-auto  titulo-localidad border-dark " >
  <h2 >  <%=Location.find(current_user.location_id).nombre_loc %></h2>
</div>
  <%end%>

<div class="card flex-md-row mb-4 box-shadow h-md-250 mx-3 ">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">Propuesta # <%= @problematic.id %></strong>
             <div class=" d-flex flex-row">
               <a href="# text-muted"> Publicada por: &nbsp;</a>
               <div class="mb-1 text-muted"><%= @problematic.usuario %>
             </div>
            </div>
              <h3 class="mb-0">
                  <%= @problematic.nombre_pr %>
              </h3>

              <p class="card-text mb-auto">
                  <%= @problematic.descripcion_pr %>
              </p>

              <div class="mb-1 text-muted">Creada: <%= @problematic.created_at %></div>
            </div>
            <%if @problematic.image.attached? %>
            <%= image_tag @problematic.image ,class:"card-img-right flex-auto d-none d-md-block", alt:"Thumbnail [500x500]" , style:"width: 500px; height: 500px;"%>
            <% else %>
            <%#POr un error no es posible cargar la imagen por defecto%>
            <%= image_tag "/../members-42919_1280.png" ,class:"card-img-right flex-auto d-none d-md-block", alt:"Thumbnail [500x500]" , style:"width: 500px; height: 500px;" %>

            <% end %>

</div>
<div class="d-flex mx-3">
  <div class="btn btn-info  mr-3 ">
      <p class=" px-2  pt-2 text-dark"> Me perjudica</p>
  </div>
  <div class="border rounded border-warning">
      <p class="mt-3 px-2">  a 582 personas les perjudica </p>
  </div>
</div>



<div class="mx-3">
  <h2 class="font-weight-bold border rounded p-1  m-2 w-50 text-center" style="border-color:#FF5A09;">Soluciones planteadas</h2>
  <hr class="" style="background:#FF5A09;">
</div>


<div class="mx-3">
  <% @problematic.solution.each do |solution|%>

      <strong> <h4><%= solution.autor_sol %></h4></strong>


    <p>
      <strong> Ideas :</strong>
      <%= solution.contenido_sol %>
    </p>
    <hr class=""style="background:#FF5A09;">
  <% end %>
</div>


<div class="form-group ml-3 w-50 jumbotron">
  <h2>Agrega un comentario o posible soluciones </h2>
  <%= form_with(model: [@problematic, @problematic.solution.build ], local: true) do |form| %>

  <div class="field">

    <%= form.label :Quien_propone_la_solucion  %>
    <%= form.text_field :autor_sol ,class:"form-control",placeholder:"Ingrese un nombre"%><br>
  </div>
  <div class="field">
    <%= form.label :Descrpcion_de_la_solucion %>
    <%= form.text_area :contenido_sol, class:"form-control", placeholder:"Ingrese una posible solucion" %>
  </div>

  <%= form.submit "Publicar soluciones o comentario" , class:"btn btn-outline-dark my-2"%>
  <% end %>
</div>


<div class="m-5">
  <%= link_to 'Back', {:controller => "problematics", :action => "index", :categoria_pr => "all"}, class:"btn btn-outline-dark" %> |
  <% if current_user.roll == 'Representante'%>
    <%= link_to 'Edit', edit_problematic_path(@problematic),class:"btn btn-outline-info" %>
    <%= link_to 'Destroy', @problematic, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-outline-danger"%>
  <%end%>
</div>