config/routes.rb
Rails.application.routes.draw do
  resources :polls do
    member do
    put "like", to: "polls#upvote"
    #put "dislike", to: "links#downvote"
  end
  end
  resources :reports
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :locations
  resources :problematics do
    resources :solutions
  end




  # resources :articles , except: [:delete] o , only: [:create] // en este cas este comando genera todas las rutas para CRUD del modelo Articles
  #Y es este caso se epecifica que se crearan todas las rutas excepto la de borrar

  get 'welcome/index'
  #get "especial", to: "welcome#index"// este comando genera que la ruta /especial sea igual que
  # escribir welcome#index

  root 'welcome#index'
  # direcciona a esta ruta la raiz de la url
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  validates :nombre_re,  presence: true
  belongs_to :location
  has_one_attached :image
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    #@reports = Report.all
    if !params[:categoria_re].present? || params[:categoria_re] =="all"
      @reports = Report.where("location_id = ?" , current_user.location_id)

    else
      @reports = Report.where("location_id = ? AND categoria_re = ?" , current_user.location_id, params[:categoria_re])

    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create

    @location = Location.find(current_user.location_id)
    @report = @location.report.new(report_params)
    @report.image.attach(params[:report][:image])


    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:location_id, :nombre_re, :descripcion_re, :like_re, :categoria_re, :usuario)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<div class="form-group mx-auto" >
  <%= form_with(model: report, local: true) do |form| %>
    <% if report.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

        <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field align-baseline">
      <%= form.label :nombre_de_noticia , class:"font-weight-bold border rounded p-1 border-dark m-2"%>
      <p class="">Asigna un nombre que identifique la nueva noticia</p>
      <%= form.text_field :nombre_re ,autofocus: true, class:"form-control w-50"%>
    </div>

    <div class="field">
      <%= form.label :descripcion_de_noticia, class:"font-weight-bold border rounded p-1 border-dark mb-2 mt-4" %>

      <%= form.text_area :descripcion_re,autofocus: true, class:"form-control",rows:"10" %>
    </div>

    <div class="field ">
      <%= form.label :carga_imagen , class:"font-weight-bold text-light border rounded p-1 border-light mb-2 mt-4"%>
      <p>Carga una imagen para dar mayor detalle a la nueva noticia</p>
      <%= form.file_field :image, class:"form-control align-middle " %>

    </div>

    <div class="field ">
      <%= form.label :categoria,class:"font-weight-bold text-light border rounded p-1 border-light mb-2 mt-4" %><br />
      <p>Seleccion la categoria a la cual pertenece esta noticia</p>
      <%= form.select(:categoria_re, options_for_select([['Movilidad','Movilidad'], ['Contaminacion', 'Contaminacion'], ['Seguridad', 'Seguridad'],['Cultura y Recreacion', 'Cultura y Recreacion'],], 1), class:"form-control ") %>

    </div>

      <%= form.hidden_field :usuario, :value => current_user.nombre_us %>

    <div class="actions my-3 text-center">
      <%= form.submit "Crea la nueva Noticia", class:"btn btn-warning " %>
    </div>
  <% end %>

</div>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center border-left border-right w-25 mx-auto  titulo-localidad border-dark " >
  <h2 >  <%=Location.find(current_user.location_id).nombre_loc %></h2>
</div>
<div class="jumbotron p-3 p-md-5 text-white rounded mx-5 d-flex flex-row " style="background:#1d1e22;">
      <div class="col-md-6 px-0 mr-5 ">
        <div class="display-4 font-italic d-flex " style="">
          <i class="fa fa-comments "></i> <h1 class="mx-3 mt-2">NOTICIAS&nbsp;</h1>
        </div>
        <p class="lead my-3">No te pierdas nada de lo que ocurre en tu localidad, infórmate de las noticias más relevantes que afecten a tu comunidad. </p>
      </div>
      <div class="input-group my-auto ml-5 d-flex flex-row">

        <div class="">

          <%= form_tag({:controller => "reports", :action => "index"}, :method => "get") %>


          <%= select_tag(:categoria_re, options_for_select([['Todas', 'all'],['Movilidad','Movilidad'], ['Contaminacion', 'Contaminacion'], ['Seguridad', 'Seguridad'],['Cultura y Recreacion', 'Cultura y Recreacion'],], 5), class:" custom-select" )%>
        </div>
        <div class="">
        <%= submit_tag "Filtrar" , class:"btn btn-warning mx-2" %>
        </div>

     </div>
</div>



<div class="card-columns mx-5 ">
  <% @reports.each do |report| %>
  <div class="card">
    <%if report.image.attached? %>
      <%= image_tag report.image ,class:"card-img-top", alt:"Card image cap" %>
    <%else %>
    <%= image_tag "https://image.freepik.com/foto-gratis/material-fondo-textura-tablon-madera_53876-33591.jpg" ,class:"card-img-top", alt:"Thumbnail [250x200]" , style:"width: 250px; height: 200px;" %>

    <%end %>
    <div class="card-body">
      <h5 class="card-title"><%= report.nombre_re %></h5>
      <p> Categoria: <%= report.categoria_re %></p>
      <%= link_to 'Mas detalles', report_path(report) , class:"btn btn-outline-danger", style:" border: #FF5A09"%>
    </div>
  </div>
  <% end %>

</div>

<div class="mx-auto " style="width:300px;">
  <%= link_to 'Crea un nueva Noticia', new_report_path, class:"btn btn-warning my-5" %>

</div>

app/views/reports/new.html.erb
<div class=" jumbotron  form-problematic  mx-5 " >
  <h2 class=" display-4 font-italic font-weight-bold text-center mb-3">Nueva Noticia</h2>

  <%= render 'form', report: @report %>

</div>


<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<div class="text-center border-left border-right w-25 mx-auto  titulo-localidad border-dark " >
  <h2 >  <%=Location.find(current_user.location_id).nombre_loc %></h2>
</div>

<div class="mx-3 my-4">
  <p class="" style="color:orange">
      <%= @report.categoria_re %>
  </p>
  <%if @report.image.attached? %>
  <%= image_tag @report.image ,class:"img-fluid rounded", alt:"Responsive image " , style:"width:600px; height450px"%>
  <% else %>
  <%#POr un error no es posible cargar la imagen por defecto%>
  <%= image_tag "/../members-42919_1280.png" ,class:"img-fluid rounded", alt:"Responsive image" , style:"width:600px; height450px" %>

  <% end %>

</div>


<div class=" mx-3">

  <div class="display-4 font-italic font-weight-bold border-bottom">
    <%= @report.nombre_re %>
  </div>

  <div class="d-flex">
    <p class="">Creada por: </p> <p class="text-info ml-3"><%= @report.usuario %></p>

  </div>

  <div class="border-bottom">
  <p class="lead text-dark"><%= @report.descripcion_re %></p>
  </div>

  <p class="text-monospace"><%= @report.created_at %></p>


</div>

<div class="m-5">
  <%= link_to 'Back', {:controller => "problematics", :action => "index", :categoria_pr => "all"}, class:"btn btn-outline-dark" %> |
  <% if current_user.roll == 'Representante'%>
    <%= link_to 'Edit', edit_report_path(@report),class:"btn btn-outline-info" %>
    <%= link_to 'destroy', reports_path , method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-outline-danger"%>
  <%end%>
</div>